import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import type { PropsWithChildren } from "react"
import "@/styles/global.css"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props
  return (
    <html
      className="color-gray-sage color-primary-green"
      lang="en"
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  )
}

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}
