import type { Metadata, Viewport } from "next"
import type { PropsWithChildren } from "react"
import { fontCssVariables } from "@/utils/fonts"
import "@/styles/global.css"

export default function RootLayout(props: PropsWithChildren) {
  const { children } = props
  return (
    <html
      className="color-gray-sage color-primary-green"
      lang="en"
    >
      <body
        className={[
          "antialiased",
          "bg-gray-2",
          "font-sans",
          "leading-1-5",
          "text-16",
          "text-gray-11",
          fontCssVariables,
        ].join(" ")}
      >
        {children}
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  width: "device-width",
}
